//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outlook2021TodoAddIn.Properties {

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get { return defaultInstance; }
        }

        /// <summary>TaskPane sichtbar</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible {
            get { return ((bool)(this["Visible"])); }
            set { this["Visible"] = value; }
        }

        /// <summary>Breite der TaskPane</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("285")]
        public int Width {
            get { return ((int)(this["Width"])); }
            set { this["Width"] = value; }
        }

        /// <summary>Ausgewählte Outlook-Konten/Stores</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Accounts {
            get { return ((global::System.Collections.Specialized.StringCollection)(this["Accounts"])); }
            set { this["Accounts"] = value; }
        }

        /// <summary>Aufgabenliste anzeigen</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTasks {
            get { return ((bool)(this["ShowTasks"])); }
            set { this["ShowTasks"] = value; }
        }

        /// <summary>Position des Splitters zwischen Terminen und Aufgaben</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SplitterDistance {
            get { return ((int)(this["SplitterDistance"])); }
            set { this["SplitterDistance"] = value; }
        }
    }
}
